name: real_estate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Italic.ttf
          style: italic
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          weight: 700
          style: italic
